### ISSUE TITLE
Ability to share a "view game" link

### ISSUE THREAD

**Issue by adamweeks** [adamweeks/thinker#3]
To invite someone or even post on twitter the "read only" mode

**Comment by joelmartinez** [comment]
:heart:

**Comment by adamweeks** [comment]
@joelmartinez I don't remember what this was about. Why couldn't we just copy/paste the game link?

**Comment by joelmartinez** [comment]
Oh, this was more of a usability thing ... _we_ know that you can simply copy/paste the browser's URL and that's the view link, however a less savvy user might not know that ... or perhaps they might be on mobile and the URL might not be easily accessible (like if they clicked on the link from twitter, or something, that built-in browser doesn't let them see the URL). So I was suggesting having a way to get at it right in the UX
